// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FloatInputBtnGroup: typeof import('./components/FloatInputBtnGroup.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    TransitionHeight: typeof import('./components/TransitionHeight.vue')['default']
    Tree: typeof import('./components/Tree.vue')['default']
    TruthTable: typeof import('./components/TruthTable.vue')['default']
  }
}

export { }
